services:
  - type: web
    name: abyte-pos
    runtime: node
    rootDir: .
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: DB_HOST
        value: serverless-us-east1.sysp0000.db2.skysql.com
      - key: DB_PORT
        value: 4059
      - key: DB_USER
        value: dbpgf25868363
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: abyte_pos
      - key: JWT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
