services:
  - type: web
    name: abyte-pos-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: DB_HOST
        value: serverless-us-east1.sysp0000.db2.skysql.com
      - key: DB_PORT
        value: 4059
      - key: DB_USER
        value: dbpgf25868363
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: abyte_pos
      - key: JWT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false

staticSites:
  - name: abyte-pos-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://abyte-pos.onrender.com
